apiVersion: v1
kind: Pod
metadata:
  name: TODO
  labels:
    tier: TODO
spec:
  containers:
  - name: TODO
    tty: true
    stdin: true
    resources:
      limits:
        nvidia.com/gpu: 1
    env:
    - name: NVIDIA_VISIBLE_DEVICES
      value: "2" # 0-7??
    - name: CUDA_VISIBLE_DEVICES
      value: "0" # has to match the above
    image: docker.pdl.cmu.edu/jingyua4/safepo:v1
    command:
    - /bin/bash
    - -c
    - wget https://raw.githubusercontent.com/BrandonBian/l2r-distributed/main/setup/setup-mamba.sh &&
      chmod +x setup-mamba.sh &&
      source ./setup-mamba.sh &&
      mamba activate l2r &&
      cd /workspace/l2r-distributed &&